version: '3.8'

services:

  db:
    image: postgres:latest
    ports:
      - "5432:5432"
    networks:
      - your-network
    environment:
      POSTGRES_DB: transactions
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
#    volumes:
#      - ./init-db:/docker-entrypoint-initdb.d

  pgadmin:
    image: dpage/pgadmin4
    ports:
      - "5050:80"
    networks:
      - your-network
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin
    depends_on:
      - db

networks:
  your-network:
    driver: bridge
